---
title: "CEO Departures"
author: "Shelby Bachman"
subtitle: "Tidy Tuesday 2021-04-27"
output:
  html_document:
    theme: flatly
    highlight: default
---
  
<hr>

```{r setup, include = FALSE}

knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)

rm(list = ls())
library(dplyr)
library(tidyr)
library(stringr)
library(ggplot2)
library(ggpubr)

# color palette
pal_departures <- c('voluntary' = '', 
                 'involuntary' = '')

```
  
```{r load_data}

departures <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-04-27/departures.csv')

departures <- departures %>%
  filter(departure_code %in% 1:6,
         fyear %in% c(1992:2018)) %>%
  rowwise() %>%
  mutate(departure_reason = case_when(
    departure_code == 1 ~ 'death',
    departure_code == 2 ~ 'illness',
    departure_code == 3 ~ 'job performance',
    departure_code == 4 ~ 'legal violations',
    departure_code == 5 ~ 'retirement',
    departure_code == 6 ~ 'new opportunity'
  )) %>%
  mutate(departure_type = case_when(
    departure_code %in% c(1, 2, 3, 4) ~ 'involuntary',
    departure_code %in% c(5, 6) ~ 'voluntary'
  )) %>%
  select(fyear,
         departure_reason,
         departure_type) %>%
  arrange(fyear)

departures_summary <- departures %>%
  group_by(fyear, departure_reason, departure_type) %>%
  summarize(n_departures = n())

```


```{r fig_time_rating, fig.height = 5, fig.width = 7}

ggplot(data = departures_summary, 
       aes(x = fyear, y = n_departures, fill = departure_reason)) +
  geom_area(alpha = 0.7, size = 0.3, colour = 'white') +
  scale_x_continuous(breaks = seq(from = 1992, to = 2018, by = 2)) +
  scale_fill_viridis_d(option = 'D') +
  labs(x = '', y = 'Number of CEO departures',
       fill = 'Reason for departure', 
       caption = 'data from doi.org/10.5281/zenodo.4543893') +
  theme_pubr() + 
  theme(text = element_text(family = 'Lato'))

```

  